apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-ci-
spec:
  entrypoint: argo-ci
  arguments:
    parameters:
    - name: revision
      value: master
    - name: repo
      value: https://github.com/robertkeithrippetoe/example-ext.git
